// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kastenhq/kubestr/pkg/csi (interfaces: FileRestoreStepper)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/kastenhq/kubestr/pkg/csi/types"
	v1 "github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1"
	v10 "k8s.io/api/core/v1"
	v11 "k8s.io/api/storage/v1"
)

// MockFileRestoreStepper is a mock of FileRestoreStepper interface.
type MockFileRestoreStepper struct {
	ctrl     *gomock.Controller
	recorder *MockFileRestoreStepperMockRecorder
}

// MockFileRestoreStepperMockRecorder is the mock recorder for MockFileRestoreStepper.
type MockFileRestoreStepperMockRecorder struct {
	mock *MockFileRestoreStepper
}

// NewMockFileRestoreStepper creates a new mock instance.
func NewMockFileRestoreStepper(ctrl *gomock.Controller) *MockFileRestoreStepper {
	mock := &MockFileRestoreStepper{ctrl: ctrl}
	mock.recorder = &MockFileRestoreStepperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRestoreStepper) EXPECT() *MockFileRestoreStepperMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockFileRestoreStepper) Cleanup(arg0 context.Context, arg1 *v10.PersistentVolumeClaim, arg2 *v10.Pod) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cleanup", arg0, arg1, arg2)
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockFileRestoreStepperMockRecorder) Cleanup(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockFileRestoreStepper)(nil).Cleanup), arg0, arg1, arg2)
}

// CreateInspectorApplication mocks base method.
func (m *MockFileRestoreStepper) CreateInspectorApplication(arg0 context.Context, arg1 *types.FileRestoreArgs, arg2 *v1.VolumeSnapshot, arg3 *v10.PersistentVolumeClaim, arg4 *v11.StorageClass) (*v10.Pod, *v10.PersistentVolumeClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInspectorApplication", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*v10.Pod)
	ret1, _ := ret[1].(*v10.PersistentVolumeClaim)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateInspectorApplication indicates an expected call of CreateInspectorApplication.
func (mr *MockFileRestoreStepperMockRecorder) CreateInspectorApplication(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInspectorApplication", reflect.TypeOf((*MockFileRestoreStepper)(nil).CreateInspectorApplication), arg0, arg1, arg2, arg3, arg4)
}

// ExecuteCopyCommand mocks base method.
func (m *MockFileRestoreStepper) ExecuteCopyCommand(arg0 context.Context, arg1 *types.FileRestoreArgs, arg2 *v10.Pod) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCopyCommand", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteCopyCommand indicates an expected call of ExecuteCopyCommand.
func (mr *MockFileRestoreStepperMockRecorder) ExecuteCopyCommand(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCopyCommand", reflect.TypeOf((*MockFileRestoreStepper)(nil).ExecuteCopyCommand), arg0, arg1, arg2)
}

// PortForwardAPod mocks base method.
func (m *MockFileRestoreStepper) PortForwardAPod(arg0 *v10.Pod, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PortForwardAPod", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PortForwardAPod indicates an expected call of PortForwardAPod.
func (mr *MockFileRestoreStepperMockRecorder) PortForwardAPod(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PortForwardAPod", reflect.TypeOf((*MockFileRestoreStepper)(nil).PortForwardAPod), arg0, arg1)
}

// ValidateArgs mocks base method.
func (m *MockFileRestoreStepper) ValidateArgs(arg0 context.Context, arg1 *types.FileRestoreArgs) (*v1.VolumeSnapshot, *v10.PersistentVolumeClaim, *v11.StorageClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateArgs", arg0, arg1)
	ret0, _ := ret[0].(*v1.VolumeSnapshot)
	ret1, _ := ret[1].(*v10.PersistentVolumeClaim)
	ret2, _ := ret[2].(*v11.StorageClass)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ValidateArgs indicates an expected call of ValidateArgs.
func (mr *MockFileRestoreStepperMockRecorder) ValidateArgs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateArgs", reflect.TypeOf((*MockFileRestoreStepper)(nil).ValidateArgs), arg0, arg1)
}
