// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kastenhq/kubestr/pkg/csi (interfaces: PVCBrowserStepper)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/kastenhq/kubestr/pkg/csi/types"
	v1 "github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1"
	v10 "k8s.io/api/core/v1"
	v11 "k8s.io/api/storage/v1"
)

// MockPVCBrowserStepper is a mock of PVCBrowserStepper interface.
type MockPVCBrowserStepper struct {
	ctrl     *gomock.Controller
	recorder *MockPVCBrowserStepperMockRecorder
}

// MockPVCBrowserStepperMockRecorder is the mock recorder for MockPVCBrowserStepper.
type MockPVCBrowserStepperMockRecorder struct {
	mock *MockPVCBrowserStepper
}

// NewMockPVCBrowserStepper creates a new mock instance.
func NewMockPVCBrowserStepper(ctrl *gomock.Controller) *MockPVCBrowserStepper {
	mock := &MockPVCBrowserStepper{ctrl: ctrl}
	mock.recorder = &MockPVCBrowserStepperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPVCBrowserStepper) EXPECT() *MockPVCBrowserStepperMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockPVCBrowserStepper) Cleanup(arg0 context.Context, arg1 *v10.PersistentVolumeClaim, arg2 *v10.Pod, arg3 *v1.VolumeSnapshot) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cleanup", arg0, arg1, arg2, arg3)
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockPVCBrowserStepperMockRecorder) Cleanup(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockPVCBrowserStepper)(nil).Cleanup), arg0, arg1, arg2, arg3)
}

// CreateInspectorApplication mocks base method.
func (m *MockPVCBrowserStepper) CreateInspectorApplication(arg0 context.Context, arg1 *types.PVCBrowseArgs, arg2 *v1.VolumeSnapshot, arg3 *v11.StorageClass) (*v10.Pod, *v10.PersistentVolumeClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInspectorApplication", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*v10.Pod)
	ret1, _ := ret[1].(*v10.PersistentVolumeClaim)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateInspectorApplication indicates an expected call of CreateInspectorApplication.
func (mr *MockPVCBrowserStepperMockRecorder) CreateInspectorApplication(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInspectorApplication", reflect.TypeOf((*MockPVCBrowserStepper)(nil).CreateInspectorApplication), arg0, arg1, arg2, arg3)
}

// ExecuteTreeCommand mocks base method.
func (m *MockPVCBrowserStepper) ExecuteTreeCommand(arg0 context.Context, arg1 *types.PVCBrowseArgs, arg2 *v10.Pod) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTreeCommand", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTreeCommand indicates an expected call of ExecuteTreeCommand.
func (mr *MockPVCBrowserStepperMockRecorder) ExecuteTreeCommand(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTreeCommand", reflect.TypeOf((*MockPVCBrowserStepper)(nil).ExecuteTreeCommand), arg0, arg1, arg2)
}

// PortForwardAPod mocks base method.
func (m *MockPVCBrowserStepper) PortForwardAPod(arg0 context.Context, arg1 *v10.Pod, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PortForwardAPod", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PortForwardAPod indicates an expected call of PortForwardAPod.
func (mr *MockPVCBrowserStepperMockRecorder) PortForwardAPod(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PortForwardAPod", reflect.TypeOf((*MockPVCBrowserStepper)(nil).PortForwardAPod), arg0, arg1, arg2)
}

// SnapshotPVC mocks base method.
func (m *MockPVCBrowserStepper) SnapshotPVC(arg0 context.Context, arg1 *types.PVCBrowseArgs, arg2 string) (*v1.VolumeSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotPVC", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1.VolumeSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnapshotPVC indicates an expected call of SnapshotPVC.
func (mr *MockPVCBrowserStepperMockRecorder) SnapshotPVC(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotPVC", reflect.TypeOf((*MockPVCBrowserStepper)(nil).SnapshotPVC), arg0, arg1, arg2)
}

// ValidateArgs mocks base method.
func (m *MockPVCBrowserStepper) ValidateArgs(arg0 context.Context, arg1 *types.PVCBrowseArgs) (*v11.StorageClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateArgs", arg0, arg1)
	ret0, _ := ret[0].(*v11.StorageClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateArgs indicates an expected call of ValidateArgs.
func (mr *MockPVCBrowserStepperMockRecorder) ValidateArgs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateArgs", reflect.TypeOf((*MockPVCBrowserStepper)(nil).ValidateArgs), arg0, arg1)
}
